language: node_js
matrix:
  include:
  - node_js: stable

before_install:
  - npm install -g npm

script:
  - gulp lint
  - gulp test:browser

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  firefox: 'latest'
